del /s /f *.cdf
del /s /f *.cache
del /s /f *.obj
del /s /f *.ilk
del /s /f *.resources
del /s /f *.tlb
del /s /f *.tli
del /s /f *.tlh
del /s /f *.tmp
del /s /f *.rsp
del /s /f *.pgc
del /s /f *.pgd
del /s /f *.meta
del /s /f *.tlog
del /s /f *.manifest
del /s /f *.res
del /s /f *.pch
del /s /f *.exp
del /s /f *.idb
del /s /f *.rep
del /s /f *.xdc
del /s /f *.pdb
del /s /f *_manifest.rc
del /s /f *.bsc
del /s /f *.sbr
del /s /f *.xml

del /s /f *.aps
del /s /f *.sdf
del /s /f *.ipch